version: '3'

services:
  api:
    container_name: api
    build: .
      
    expose:
      - 80

    volumes:
      - ./:/app
    
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
  