version: '3'
services:
  sample-app:
    container_name: sample-app
    build:
      context: .
    command: "yarn start"
    environment:
      - AUTHENTICATION_STRATEGY=local
      - SESSION_SECRET_DIR=./../session-secret
      - SESSION_STORE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    expose:
      - 3000

    volumes:
      - ./src/:/app
    
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
