version: '3'
services:
  nginx:
    container_name: nginx
    
    build:
      context: .
    ports:
      - 3000:80

    volumes:
      - ./local/html:/usr/share/nginx/html/
      - ./local/conf.d:/etc/nginx/conf.d
  
    networks:
      - nginx-network

    env_file:
      - ../.env

networks:
  nginx-network:
    external: true
